name: lando-redis-6
services:
  defaults:
    type: redis:6
  patch:
    type: redis:6.0.15
  password:
    type: redis:6
    creds:
      password: nerfherder

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/redis": ./../../
