name: lando-redis-4
services:
  defaults:
    type: redis:4
  patch:
    type: redis:4.0.11

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/redis": ./../../