name: lando-redis-7
services:
  defaults:
    type: redis:7
  patch:
    type: redis:7.0.10
  password:
    type: redis:7
    creds:
      password: nerfherder

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/redis": ./../../
