name: lando-redis-2
services:
  defaults:
    type: redis:2.8
  patch:
    type: redis:2.8.22
  password:
    type: redis:2.8
    password: nerfherder

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/redis": ./../../
